using System.Text.Json.Serialization;

namespace XO.Diagnostics.Bugsnag.Models;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum BugsnagRuntimeName
{
    androidApiLevel,
    bottle,
    celery,
    clangVersion,
    cocos2dx,
    delayedJob,
    django,
    dotnet,
    dotnetApiCompatibility,
    dotnetClr,
    dotnetScriptingRuntime,
    eventMachine,
    flask,
    gin,
    go,
    javaType,
    javaVersion,
    jruby,
    laravel,
    lumen,
    magento,
    mailman,
    martini,
    negroni,
    node,
    osBuild,
    php,
    python,
    que,
    rack,
    rails,
    rake,
    reactNative,
    reactNativeJsEngine,
    resque,
    revel,
    ruby,
    shoryoken,
    sidekiq,
    silex,
    sinatra,
    springBoot,
    springFramework,
    swift,
    symfony,
    tornado,
    unity,
    unityScriptingBackend,
    wordpress,
}

